### ISSUE TITLE
Warnings in wrench

### ISSUE THREAD

**Issue by zdk123** [HCBravoLab/Wrench#2]
I'm getting some noisy output when running wrench with the default parameters even on the example data from the vignette, as well as other datasets I've tried.

```
counts <- MRcounts( mouseData, norm=FALSE )
group <- pData(mouseData)$diet
W <- wrench( counts, condition=group  )
```

```
Warning messages:
1: glm.fit: algorithm did not converge
2: glm.fit: fitted probabilities numerically 0 or 1 occurred
3: glm.fit: algorithm did not converge
4: glm.fit: fitted probabilities numerically 0 or 1 occurred
5: Partial NA coefficients for 8430 probe(s)
```
How should I interpret Warnings 1-4: if glm.fit doesn't converge, can I still trust the weights used for the normalization factors?

I'd appreciate any guidance you can offer on this.

**Comment by hcorrada** [comment]
In our experience, robust averaging seems to deal with these issues well. See https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-5160-5#Sec17
